### ISSUE TITLE
Other events besides hover?

### ISSUE THREAD

**Issue by davewhitley** [iliasiovis/Hoverizr#1]
Can Hoverizr be easily modified to include other events besides `:hover`? For example, `:checked`?

This is a really great plugin by the way. Thanks!

**Comment by iliasiovis** [comment]
Well of course it could be modified. Actually :checked is not an event for jquery but maybe this could help you:
http://stackoverflow.com/questions/3000538/how-to-bind-to-checked-for-a-checkbox-only

The hover effect could be swapped with something else bindable. Check out lines 178 - 191 where the hover effect is and replace it with whatever you like.

Sorry I can't give you a full example myself. I am swamped in work and projects so no time to try it out.

If you manage to make it, please send me an email and show me what you did :) Would be happy to see it in action! Oh, and thanks for your kind words.

**Comment by developher-net** [comment]
If you make the hover event optional, then people can write their own behaviors without modifying the core script.
