### ISSUE TITLE
licence could not find

### ISSUE THREAD

**Issue by LeaYeh** [iliasiovis/Hoverizr#7]
we are cdnjs team (https://github.com/cdnjs/cdnjs), we want to host/add your project Hoverizr on cdnjs,
but here is a problem that we need clearly licence,
could you please help me to figure it out?

**Comment by iliasiovis** [comment]
Hi,

feel free to add and host hoverizr. It was released under Creative Commons CC BY.

**Comment by LeaYeh** [comment]
@iliasiovis thank your contributions!
i have sent pr by [this](https://github.com/cdnjs/cdnjs/pull/6129)

**Comment by LeaYeh** [comment]
@iliasiovis hi, we couldn't recognize "CC-BY" from our [license-list](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json) could you point out which version you use?

**Comment by iliasiovis** [comment]
@LeaYeh hi, just use CC-BY-4.0. It should be fine.
